### ISSUE TITLE
VSCode-Maxim-v130-windows.zip content

### ISSUE THREAD

**Issue by fneirab** [MaximIntegratedTechSupport/VSCode-Maxim#5]
In the most recent version of the windows download. The readme instructions show the MaximSDK folder contains both Examples and Libraries. There is only examples. 
VSCode-Maxim-v130-windows.zip\VSCode-Maxim-v130-windows\MaximSDK
![image](https://user-images.githubusercontent.com/23093027/158906149-ae287274-f60e-4575-bcb2-4344210190cb.png)

The instructions also mentioned to copy and overwrite, but the examples only contain the .vscode folder on each of the examples, so it will practically erase the MaximSDK default code. 

![image](https://user-images.githubusercontent.com/23093027/158906068-23ab570a-c462-4327-87b0-4dfbbd67e3d7.png)

**Comment by Jake-Carter** [comment]
Thanks @fneirab,

I'll get those screenshots updated.

On the copy & overwrite - doing so will actually just place the .vscode folder inside of each example folder.  It won't erase any of the example folder's content.  It "merges" the folders together, but it doesn't replace the Example folder entirely.

**Comment by Jake-Carter** [comment]
Image updated:

https://github.com/MaximIntegratedTechSupport/VSCode-Maxim/commit/24a92da8721e4b1c6b5e154a8a86d90184cc1c03
